enum ActionTypes {
  GET_LNB_YN = 'app/GET_LNB_YN',
  OPEN_ALERT_POPUP = 'app/OPEN_ALERT_POPUP',
  CLOSE_ALERT_POPUP = 'app/CLOSE_ALERT_POPUP',
  OPEN_CONFIRM_POPUP = 'app/OPEN_CONFIRM_POPUP',
  CLOSE_CONFIRM_POPUP = 'app/CLOSE_CONFIRM_POPUP',
  SET_LOGIN_YN = 'app/SET_LOGIN_YN',
  SET_NAV_INFO = 'app/SET_NAV_INFO',
  SET_TAB_INFO = 'app/SET_TAB_INFO',
  UPDATE_SELECTED_TAB = 'app/UPDATE_SELECTED_TAB',
  SET_LAYOUT_HEIGHT = 'app/SET_LAYOUT_HEIGHT',
}

export default ActionTypes;
